// frontend/src/components/BuyerView.vue
<template>
  <div class="mx-auto max-w-6xl px-4 py-8 sm:px-6">
    <div class="mb-8">
      <h1 class="font-serif text-3xl font-semibold text-primary">Enchères en cours</h1>
      <p class="text-neutral-500">Découvrez les lots disponibles aux enchères</p>
    </div>

    <!-- Search & Filter -->
    <div class="mb-6 flex flex-wrap gap-4 items-center">
      <Input v-model="searchQuery" placeholder="Rechercher un lot..." class="max-w-sm" />
      <select v-model="selectedCategory" class="h-10 rounded-md border border-border bg-card px-3 py-2 text-sm text-primary">
        <option value="">Toutes les catégories</option>
        <option v-for="cat in appStore.CATEGORIES" :key="cat" :value="cat">{{ cat }}</option>
      </select>
    </div>

    <!-- Lots Grid -->
    <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
      <Card v-for="lot in filteredLots" :key="lot.id" class="overflow-hidden hover:shadow-md transition-shadow">
        <div class="aspect-[4/3] overflow-hidden bg-muted">
          <img :src="lot.image || '/placeholder.svg'" :alt="lot.title" class="h-full w-full object-cover" />
        </div>
        <CardContent class="p-5">
          <div class="flex items-center gap-2 mb-2">
            <Badge :variant="appStore.STATUS_VARIANTS[lot.status]">
              {{ appStore.STATUS_LABELS[lot.status] }}
            </Badge>
            <span class="text-xs text-neutral-500">{{ lot.category }}</span>
          </div>
          <h3 class="font-serif text-lg font-semibold text-primary mb-2">{{ lot.title }}</h3>
          <p class="text-sm text-neutral-500 mb-4 line-clamp-2">{{ lot.description }}</p>

          <div class="flex items-center justify-between mb-4">
            <div>
              <p class="text-xs text-neutral-500">Prix actuel</p>
              <p class="font-bold text-xl text-accent">{{ appStore.formatPrice(lot.currentBid) }}</p>
            </div>
            <div class="text-right">
              <p class="text-xs text-neutral-500">Temps restant</p>
              <p class="font-medium text-accent">{{ appStore.timeLeft(lot.endsAt) }}</p>
            </div>
          </div>

          <div class="flex gap-2">
            <Button variant="accent" class="flex-1" @click="openLotDetail(lot)">Enchérir</Button>
            <Button variant="ghost" size="icon" @click="openLotDetail(lot)">
              <svg class="size-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                <circle cx="12" cy="12" r="3"></circle>
              </svg>
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>

    <!-- Lot Detail Dialog -->
    <LotDetailDialog
      :open="selectedLot !== null"
      :lot="selectedLot"
      @update:open="selectedLot = null"
    />
  </div>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useAppStore } from '@/stores/app'
import Card from '@/components/ui/Card.vue'
import CardContent from '@/components/ui/CardContent.vue'
import Button from '@/components/ui/Button.vue'
import Badge from '@/components/ui/Badge.vue'
import Input from '@/components/ui/Input.vue'
import LotDetailDialog from '@/components/LotDetailDialog.vue'

const appStore = useAppStore()
const searchQuery = ref('')
const selectedCategory = ref('')
const selectedLot = ref(null)

const filteredLots = computed(() => {
  return appStore.lots.filter(lot => {
    if (lot.status !== 'live') return false
    if (searchQuery.value && !lot.title.toLowerCase().includes(searchQuery.value.toLowerCase())) return false
    if (selectedCategory.value && lot.category !== selectedCategory.value) return false
    return true
  })
})

function openLotDetail(lot) {
  selectedLot.value = lot
}
</script>

// auction-app-mockups/components/buyer-view.tsx
"use client"

import { useMemo, useState } from "react"
import Image from "next/image"
import { Clock, Search } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { LotDetailDialog } from "@/components/lot-detail-dialog"
import { useApp } from "@/lib/store"
import { CATEGORIES } from "@/lib/data"
import { formatPrice, timeLeft } from "@/lib/format"
import type { Lot } from "@/lib/types"

export function BuyerView() {
  const { lots, user } = useApp()
  const [query, setQuery] = useState("")
  const [category, setCategory] = useState("all")
  const [selected, setSelected] = useState<Lot | null>(null)
  const [open, setOpen] = useState(false)

  const liveLots = useMemo(
    () =>
      lots
        .filter((l) => l.status === "live")
        .filter((l) =>
          category === "all" ? true : l.category === category,
        )
        .filter((l) =>
          query.trim()
            ? l.title.toLowerCase().includes(query.trim().toLowerCase())
            : true,
        ),
    [lots, category, query],
  )

  function openLot(lot: Lot) {
    setSelected(lot)
    setOpen(true)
  }

  return (
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      <div className="flex flex-col gap-1">
        <h1 className="font-serif text-3xl font-semibold">
          Ventes en cours
        </h1>
        <p className="text-muted-foreground">
          Bonjour {user?.name.split(" ")[0]}, voici les lots ouverts aux
          enchères.
        </p>
      </div>

      <div className="mt-6 flex flex-col gap-3 sm:flex-row">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Rechercher un lot…"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="pl-9"
          />
        </div>
        <Select value={category} onValueChange={(v) => setCategory(v ?? "all")}>
          <SelectTrigger className="sm:w-56">
            <SelectValue placeholder="Catégorie">
              {(value: string) =>
                value === "all" ? "Toutes les catégories" : value
              }
            </SelectValue>
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">Toutes les catégories</SelectItem>
            {CATEGORIES.map((c) => (
              <SelectItem key={c} value={c}>
                {c}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {liveLots.length === 0 ? (
        <p className="mt-12 text-center text-muted-foreground">
          Aucun lot ne correspond à votre recherche.
        </p>
      ) : (
        <div className="mt-6 grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {liveLots.map((lot) => (
            <Card
              key={lot.id}
              onClick={() => openLot(lot)}
              className="group cursor-pointer overflow-hidden pt-0 transition-shadow hover:shadow-lg"
            >
              <div className="relative aspect-[4/3] overflow-hidden bg-secondary">
                <Image
                  src={lot.image || "/placeholder.svg"}
                  alt={lot.title}
                  fill
                  className="object-cover transition-transform duration-300 group-hover:scale-105"
                  sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
                />
                <Badge className="absolute left-3 top-3 gap-1">
                  <Clock className="size-3" />
                  {timeLeft(lot.endsAt)}
                </Badge>
              </div>
              <CardContent className="flex flex-col gap-1">
                <span className="text-xs uppercase tracking-wide text-muted-foreground">
                  {lot.category}
                </span>
                <h3 className="line-clamp-1 font-serif text-lg font-medium">
                  {lot.title}
                </h3>
                <div className="mt-2 flex items-end justify-between">
                  <div>
                    <p className="text-xs text-muted-foreground">
                      Enchère actuelle
                    </p>
                    <p className="font-semibold text-primary">
                      {formatPrice(lot.currentBid)}
                    </p>
                  </div>
                  <span className="text-xs text-muted-foreground">
                    {lot.bids.length} enchère{lot.bids.length > 1 ? "s" : ""}
                  </span>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <LotDetailDialog lot={selected} open={open} onOpenChange={setOpen} />
    </div>
  )
}
