// frontend/src/components/SellerView.vue
<template>
  <div class="mx-auto max-w-6xl px-4 py-8 sm:px-6">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <h1 class="font-serif text-3xl font-semibold text-primary">Mes lots</h1>
        <p class="text-neutral-500">
          Gérez vos mises en vente et suivez les enchères.
        </p>
      </div>
      <CreateLotDialog />
    </div>

    <!-- Stats -->
    <div class="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">
      <StatCard label="Lots déposés" :value="String(stats.total)" />
      <StatCard label="En vente" :value="String(stats.live)" />
      <StatCard label="Enchères reçues" :value="String(stats.bids)" />
      <StatCard label="Produit des ventes" :value="appStore.formatPrice(stats.revenue)" />
    </div>

    <!-- Lots List -->
    <div class="mt-8 flex flex-col gap-3">
      <div v-if="myLots.length === 0" class="rounded-lg border border-border bg-card p-6">
        <p class="py-12 text-center text-neutral-500">
          Vous n'avez encore aucun lot. Cliquez sur "Mettre un lot en vente" pour commencer.
        </p>
      </div>
      <Card v-else v-for="lot in myLots" :key="lot.id" class="overflow-hidden py-0">
        <CardContent class="flex flex-col gap-4 p-4 sm:flex-row sm:items-center">
          <div class="relative h-20 w-28 shrink-0 overflow-hidden rounded-md bg-muted">
            <img
              :src="lot.image || '/placeholder.svg'"
              :alt="lot.title"
              class="h-full w-full object-cover"
            />
          </div>
          <div class="flex-1">
            <div class="flex items-center gap-2">
              <Badge :variant="appStore.STATUS_VARIANTS[lot.status]">
                {{ appStore.STATUS_LABELS[lot.status] }}
              </Badge>
              <span class="text-xs text-neutral-500">
                {{ lot.category }}
              </span>
            </div>
            <h3 class="mt-1 font-serif text-lg font-semibold text-primary">
              {{ lot.title }}
            </h3>
            <p class="text-sm text-neutral-500">
              {{ lot.status === 'live' ? `Clôture dans ${appStore.timeLeft(lot.endsAt)}` : lot.status === 'pending' ? 'En attente de validation' : appStore.STATUS_LABELS[lot.status] }}
            </p>
          </div>
          <div class="flex items-center gap-6">
            <div class="text-right">
              <p class="text-xs text-neutral-500">
                {{ lot.bids.length > 0 ? 'Meilleure enchère' : 'Mise à prix' }}
              </p>
              <p class="font-bold text-accent">
                {{ appStore.formatPrice(lot.currentBid) }}
              </p>
            </div>
            <Button
              variant="ghost"
              size="icon"
              aria-label="Retirer le lot"
              @click="handleRemove(lot)"
            >
              <svg class="size-4 text-danger" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <polyline points="3 6 5 6 21 6"></polyline>
                <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path>
              </svg>
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useAppStore } from '@/stores/app'
import Card from '@/components/ui/Card.vue'
import CardContent from '@/components/ui/CardContent.vue'
import Button from '@/components/ui/Button.vue'
import Badge from '@/components/ui/Badge.vue'
import CreateLotDialog from '@/components/CreateLotDialog.vue'
import StatCard from '@/components/StatCard.vue'

const appStore = useAppStore()

const myLots = computed(() => appStore.lots.filter(l => l.seller === appStore.user?.email))

const stats = computed(() => {
  const live = myLots.value.filter(l => l.status === 'live').length
  const revenue = myLots.value.filter(l => l.status === 'sold').reduce((sum, l) => sum + l.currentBid, 0)
  const bids = myLots.value.reduce((sum, l) => sum + l.bids.length, 0)
  return { live, revenue, bids, total: myLots.value.length }
})

function handleRemove(lot) {
  if (confirm(`Retirer le lot "${lot.title}" ?`)) {
    appStore.removeLot(lot.id)
  }
}
</script>

// auction-app-mockups/components/seller-view.tsx
"use client"

import { useMemo } from "react"
import Image from "next/image"
import { Trash2 } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { CreateLotDialog } from "@/components/create-lot-dialog"
import { useApp } from "@/lib/store"
import {
  STATUS_LABELS,
  formatPrice,
  statusVariant,
  timeLeft,
} from "@/lib/format"

export function SellerView() {
  const { lots, user, removeLot } = useApp()

  const myLots = useMemo(
    () => lots.filter((l) => l.seller === user?.email),
    [lots, user],
  )

  const stats = useMemo(() => {
    const live = myLots.filter((l) => l.status === "live")
    const revenue = myLots
      .filter((l) => l.status === "sold")
      .reduce((sum, l) => sum + l.currentBid, 0)
    const bids = myLots.reduce((sum, l) => sum + l.bids.length, 0)
    return { live: live.length, revenue, bids, total: myLots.length }
  }, [myLots])

  function handleRemove(id: string, title: string) {
    removeLot(id)
    toast.success(`« ${title} » a été retiré.`)
  }

  return (
    <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="font-serif text-3xl font-semibold">Mes lots</h1>
          <p className="text-muted-foreground">
            Gérez vos mises en vente et suivez les enchères.
          </p>
        </div>
        <CreateLotDialog />
      </div>

      <div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4">
        <StatCard label="Lots déposés" value={String(stats.total)} />
        <StatCard label="En vente" value={String(stats.live)} />
        <StatCard label="Enchères reçues" value={String(stats.bids)} />
        <StatCard label="Produit des ventes" value={formatPrice(stats.revenue)} />
      </div>

      <div className="mt-8 flex flex-col gap-3">
        {myLots.length === 0 ? (
          <Card>
            <CardContent className="py-12 text-center text-muted-foreground">
              Vous n&apos;avez encore aucun lot. Cliquez sur « Mettre un lot en
              vente » pour commencer.
            </CardContent>
          </Card>
        ) : (
          myLots.map((lot) => (
            <Card key={lot.id} className="overflow-hidden py-0">
              <CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center">
                <div className="relative h-20 w-28 shrink-0 overflow-hidden rounded-md bg-secondary">
                  <Image
                    src={lot.image || "/placeholder.svg"}
                    alt={lot.title}
                    fill
                    className="object-cover"
                    sizes="112px"
                  />
                </div>
                <div className="flex-1">
                  <div className="flex items-center gap-2">
                    <Badge variant={statusVariant(lot.status)}>
                      {STATUS_LABELS[lot.status]}
                    </Badge>
                    <span className="text-xs text-muted-foreground">
                      {lot.category}
                    </span>
                  </div>
                  <h3 className="mt-1 font-serif text-lg font-medium">
                    {lot.title}
                  </h3>
                  <p className="text-sm text-muted-foreground">
                    {lot.status === "live"
                      ? `Clôture dans ${timeLeft(lot.endsAt)}`
                      : lot.status === "pending"
                        ? "En attente de validation"
                        : STATUS_LABELS[lot.status]}
                  </p>
                </div>
                <div className="flex items-center gap-6">
                  <div className="text-right">
                    <p className="text-xs text-muted-foreground">
                      {lot.bids.length > 0 ? "Meilleure enchère" : "Mise à prix"}
                    </p>
                    <p className="font-semibold text-primary">
                      {formatPrice(lot.currentBid)}
                    </p>
                  </div>
                  <Button
                    variant="ghost"
                    size="icon"
                    aria-label="Retirer le lot"
                    onClick={() => handleRemove(lot.id, lot.title)}
                  >
                    <Trash2 className="size-4 text-destructive" />
                  </Button>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>
    </div>
  )
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <Card>
      <CardContent className="py-4">
        <p className="text-xs uppercase tracking-wide text-muted-foreground">
          {label}
        </p>
        <p className="mt-1 font-serif text-2xl font-semibold">{value}</p>
      </CardContent>
    </Card>
  )
}
